### ISSUE TITLE
How to deploy new code

### ISSUE THREAD

**Issue by thomasmhr** [karmi/chef-hello-cloud#1]
Hi,

This chef example is really awesome :-) I will digg more on it later. But right now I have question. The scenario for the first deploy of the app is more or less clear in my mind. But how in this scenario, would you deploy new code or a bug fix ?

Thanks for sharing that.  (and sorry about using the issue feature for a simple question)

**Comment by karmi** [comment]
Hey, no worries using issues for questions .)

The beauty of Chef is that an "update deploy" is just a regular `sudo chef-client`: the [`sync`](http://wiki.opscode.com/display/chef/Deploy+Resource#DeployResource-Actions) action will just do a git fetch & reset.

**Comment by thomasmhr** [comment]
Brilliant. I will play with it as soon as I can. I guess there is a similar action to restart the process ...

thanks

**Comment by karmi** [comment]
Yes, you can use the `GitChanged` extension to restart the application when the code has been changed:

``` ruby
# Restart application if code has changed
#
bash "restart application" do
  code "service application restart"

  only_if do
    node.application[:previous_revision] != node.application[:current_revision]
  end
end
```
