### ISSUE TITLE
Vagrant can't run with active_support

### ISSUE THREAD

**Issue by edyu** [karmi/chef-hello-cloud#3]
Not sure why but whenever I try to run the step with vagrant up, I get the following error and I'm 100% certain I installed the activesupport gem. I can even use irb and do the require statement and it works.
## [!] ERROR -- Please install ActiveSupport (gem install activesupport)

Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/ed/dev/chef/chef-hello-cloud/Vagrantfile
Message: cannot load such file -- active_support/core_ext/hash/deep_merge

**Comment by edyu** [comment]
Actually this might be a vagrant problem itself. :(

**Comment by karmi** [comment]
Hey, Vagrant switched to standalone installations lately, so there might be an issue there...

**Comment by edyu** [comment]
Yup, the embedded vagrant doesn't not include activesupport so ...
I guess I'll just have to copy paste the code for deep merge or write my own deep merge method.

**Comment by karmi** [comment]
... or just install the older version with `gem install vagrant`, it should still work fine.

**Comment by edyu** [comment]
Actually it doesn't because with all of the dependencies it will install a real old version of virtualbox and vagrant gems which don't work with the new version of virtualbox.

**Comment by edyu** [comment]
Vagrant experienced an error!

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
If VirtualBox is installed, it may be an incorrect version. Vagrant currently
requires VirtualBox 3.2.x. Please install the proper version to continue.

**Comment by edyu** [comment]
And the current version of VirtualBox is 4.2.12.

**Comment by karmi** [comment]
But the older VirtualBox versions can still be downloaded+installed? I depend on the deep merge method in the Chef cookbook as well, wondering what issues I'll hit there :)

**Comment by edyu** [comment]
I'm using https://github.com/Offirmo/hash-deep-merge/blob/master/lib/hash_deep_merge.rb right now to make it work in Vagrantfile itself.

**Comment by edyu** [comment]
On the second server so far so good.

**Comment by edyu** [comment]
I tried plugin for vagrant and did vagrant plugin install activesupport and obviously that didn't work

**Comment by ilovemysillybanana** [comment]
@edyu can you give an explanation of how you installed that new implementation of deep merge into vagrant?
