### ISSUE TITLE
Not finding plugin_aws recipe.

### ISSUE THREAD

**Issue by edyu** [karmi/chef-hello-cloud#4]
## Chef::Exceptions::RecipeNotFound

could not find recipe plugin_aws for cookbook elasticsearch

**Comment by yoshie902a** [comment]
Update your roles...

"recipe[elasticsearch::plugin_aws]",
"recipe[elasticsearch::proxy_nginx]",

to
"recipe[elasticsearch::aws]",
"recipe[elasticsearch::proxy]",

**Comment by edyu** [comment]
it's been too long so I'm closing this issue. Haven't tested it since the error happened.
